#pragma once

#define IMG_ICON_COMP_PNG 300
#define IMG_LOGO_PNG 301
#define IMG_LOGO_LONG_PNG 302
#define FONT_FA_SOLID_900_OTF 500
#define FONT_JETBRAINS_MONO_REGULAR_TTF 501
#define SHADER_BLIT_FRAG 700
#define SHADER_FULLSCREEN_VERT 701
#define SHADER_TRIANGLE_FRAG 702
#define SHADER_TRIANGLE_VERT 703
